
apiVersion: v1
kind: Service
metadata:
  name: wso2am-gw-separated-mysql-service
  namespace: wso2
spec:
  type: ClusterIP
  selector:
    deployment: wso2am-mysql
    product: api-manager
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
---
