
apiVersion: v1
kind: Service
metadata:
  name: wso2am-gw-separated-pstmkm-service
  namespace: wso2
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: wso2am-gw-separated-pstmkm
    product: api-manager
  ports:
    # ports that this service should serve on
    -
      name: servlet-http
      protocol: TCP
      port: 9763
      targetPort: 9763
    -
      name: servlet-https
      protocol: TCP
      port: 9443
      targetPort: 9443

    - name: throttle-ssl
      protocol: TCP
      port: 9711
      targetPort: 9711

    - name: throttle-tcp
      protocol: TCP
      port: 9611
      targetPort: 9611

    - name: throttle-decision-secure
      protocol: TCP
      port: 5672
      targetPort: 5672

    - name: throttle-decision-non-secure
      protocol: TCP
      port: 5672
      targetPort: 5672

