apiVersion: v1
kind: Service
metadata:
  name: {{ template "am-pattern-4.resource.prefix" . }}-am-redis-service
  namespace : {{ .Release.Namespace }}
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: {{ template "am-pattern-4.resource.prefix" . }}-am-redis
  ports:
    # ports that this service should serve on
    - name: redis-service
      protocol: TCP
      port: 6379