apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "am-pattern-4.resource.prefix" . }}-client-manage-pod-artifacts-storage-volume-claim
  namespace: {{ .Release.Namespace }}
  labels:
    deployment: {{ template "am-pattern-4.resource.prefix" . }}-client-manage-pod-artifacts-storage-volume
spec:
  storageClassName: "azurefile-csi-premium"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi