apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "am-pattern-4.resource.prefix" . }}-am-cp-log-storage-volume-claim
  namespace: wso2
  labels:
    deployment: {{ template "am-pattern-4.resource.prefix" . }}-am-cp
spec:
  storageClassName: "azurefile-csi-premium"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi