apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2am-gw-separated-gw-log-storage-claim
  namespace: wso2
  labels:
    deployment: wso2am-pattern-1-am
    product: api-manager
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: wso2am-gw-separated-gw-log-storage