apiVersion: v1
kind: ConfigMap
metadata:
  name: wso2am-gw-separated-gw-deployment-conf
  namespace: wso2
data:
  deployment.toml: |
    [server]
    hostname = "wso2am-gw-server"
    node_ip = "$env{NODE_IP}"
    # offset=0
    mode = "single" #single or ha
    base_path = "${carbon.protocol}://${carbon.host}:${carbon.management.port}"
    #discard_empty_caches = false
    server_role = "default"

    [super_admin]
    username = "admin"
    password = "admin"
    create_admin_account = true

    [user_store]
    type = "database_unique_id"

    [database.apim_db]
    type = "mysql"
    url = "jdbc:mysql://wso2am-gw-separated-mysql-service:3306/WSO2AM_DB?autoReconnect=true&amp;useSSL=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"

    [database.shared_db]
    type = "mysql"
    url = "jdbc:mysql://wso2am-gw-separated-mysql-service:3306/WSO2AM_SHARED_DB?autoReconnect=true&amp;useSSL=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"

    [keystore.tls]
    file_name =  "wso2carbon.jks"
    type =  "JKS"
    password =  "wso2carbon"
    alias =  "wso2carbon"
    key_password =  "wso2carbon"
    
    [truststore]
    file_name = "client-truststore.jks"
    type = "JKS"
    password = "wso2carbon"
    
    [apim.key_manager]
    service_url = "https://wso2am-gw-separated-pstmkm-service:9443/services/"
    
    [apim.throttling]
    service_url = "https://localhost:9443/services/"
    throttle_decision_endpoints = ["tcp://localhost:5672"]
    
    [[apim.throttling.url_group]]
    traffic_manager_urls=["tcp://localhost:9611"]
    traffic_manager_auth_urls=["ssl://localhost:9711"]

    [apim.cors]
    allow_origins = "*"
    allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
    allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction","apikey", "testKey"]
    allow_credentials = false

    [transport.https.properties]
    proxyPort = 443