apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "am-pattern-4.resource.prefix" . }}-am-pc-2-trafficmanager-log-storage-volume-claim
  namespace: {{ .Release.Namespace }}
  labels:
    deployment: {{ template "am-pattern-4.resource.prefix" . }}-am-pc-2-trafficmanager
spec:
  storageClassName: "azurefile-csi-premium"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 70Gi