# Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2apim-manager-worker
  namespace: wso2
  labels:
    app: wso2apim-gw
    node: manager-worker
    pattern: wso2apim-pattern-3
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wso2apim-gw
      node: manager-worker
      app-sv: wso2apim-gw-sv
  template:
    metadata:
      labels:
        app: wso2apim-gw
        node: manager-worker
        app-sv: wso2apim-gw-sv
    spec:
      containers:
      -
        image: virajhasith/wso2am-2.5.0:1621359805584withLogPatches
#        image: virajhasith/wso2am-2.5.0:1621359805584withPatches
#        image: virajhasith/wso2am-2.5.0:1621359805584
        name: wso2apim
        imagePullPolicy: IfNotPresent
        ports:
        -
          containerPort: 8280
          protocol: "TCP"
        -
          containerPort: 8243
          protocol: "TCP"
        -
          containerPort: 9763
          protocol: "TCP"
        -
          containerPort: 9443
          protocol: "TCP"
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 150
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9443
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 150
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9443
          timeoutSeconds: 30
        resources:
          limits:
            cpu: "4"
            memory: 12Gi
          requests:
            cpu: "3"
            memory: 8Gi

        volumeMounts:
        - name: apim-synapse-configs-storage-volume
          mountPath: "/home/wso2carbon/wso2am-2.5.0/repository/deployment/server"
        - name: apim-gw-log-storage-volume
          mountPath: "/home/wso2carbon/wso2am-2.5.0/repository/logs"
        - name: apim-gw-manager-worker-bin
          mountPath: "/home/wso2carbon/kubernetes-volumes/am/bin/"
        - name: apim-gw-manager-worker-conf
          mountPath: "/home/wso2carbon/kubernetes-volumes/am/conf/"
        - name: apim-gw-manager-worker-identity
          mountPath: "/home/wso2carbon/kubernetes-volumes/am/conf-identity/"
        - name: apim-gw-manager-worker-axis2
          mountPath: "/home/wso2carbon/kubernetes-volumes/am/conf-axis2/"
        - name: apim-gw-manager-worker-datasources
          mountPath: "/home/wso2carbon/kubernetes-volumes/am/conf-datasources/"
        - name: apim-gw-manager-worker-tomcat
          mountPath: "/home/wso2carbon/kubernetes-volumes/am/conf-tomcat/"
        - name: db-connector-jar
          mountPath: "/home/wso2carbon/kubernetes-volumes/am/mounting-jar"
        - name: mounting-custom-log-jar
          mountPath: "/home/wso2carbon/kubernetes-volumes/am/mounting-log-jar"
        - name: apim-conf-entrypoint
          mountPath: "/home/wso2carbon/docker-entrypoint.sh"
          subPath: docker-entrypoint.sh
      serviceAccountName: "wso2svcacct"
      volumes:
      - name: apim-synapse-configs-storage-volume
        persistentVolumeClaim:
          claimName: apim-synapse-configs-storage-claim
      - name: apim-gw-log-storage-volume
        persistentVolumeClaim:
          claimName: apim-gw-log-storage-claim
      - name: apim-gw-manager-worker-bin
        configMap:
          name: apim-gw-manager-worker-bin
      - name: apim-gw-manager-worker-conf
        configMap:
          name: apim-gw-manager-worker-conf
      - name: apim-gw-manager-worker-identity
        configMap:
          name: apim-gw-manager-worker-identity
      - name: apim-gw-manager-worker-axis2
        configMap:
          name: apim-gw-manager-worker-axis2
      - name: apim-gw-manager-worker-datasources
        configMap:
          name: apim-gw-manager-worker-datasources
      - name: apim-gw-manager-worker-tomcat
        configMap:
          name: apim-gw-manager-worker-tomcat
      - name: db-connector-jar
        configMap:
          name: db-connector-jar
      - name: mounting-custom-log-jar
        configMap:
          name: mounting-custom-log-jar
      - name: apim-conf-entrypoint
        configMap:
          name: apim-conf-entrypoint
          defaultMode: 0407
