apiVersion: v1
kind: PersistentVolume
metadata:
  name: netstat-captured-data-storage
  namespace: wso2
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fss.csi.oraclecloud.com
    volumeHandle: ocid1.filesystem.oc1.iad.aaaaaaaaaafh5ol5nfqwillqojxwiotjmfsc2ylefuzqaaaa:10.0.20.218:/gw-separated-gw-netshoot/netstat-captured-data-storage